{"name": "No se permite agregar más de un cónyuge", "status": "failed", "statusDetails": {"message": "AssertionError: No se mostró el mensaje 'Hay más de un perfil con la relación Conyugé. Solo puede haber uno.'\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 70, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n"}, "steps": [{"name": "Given que el usuario accede al formulario de Queplan", "status": "passed", "start": 1751549951188, "stop": 1751549951813}, {"name": "When ingresa datos de contratante con rut \"17470576-3\"", "status": "passed", "start": 1751549951813, "stop": 1751549979729}, {"name": "And ingresa datos de beneficiario con rut \"15046896-5\"", "status": "passed", "start": 1751549979729, "stop": 1751549996566}, {"name": "And agrega otro cónyuge con rut \"6065750-5\"", "status": "passed", "start": 1751549996566, "stop": 1751550006901}, {"name": "Then debe mostrarse el mensaje de error \"Hay más de un perfil con la relación Conyugé. Solo puede haber uno.\"", "status": "failed", "statusDetails": {"message": "AssertionError: No se mostró el mensaje 'Hay más de un perfil con la relación Conyugé. Solo puede haber uno.'\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 70, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n"}, "start": 1751550006901, "stop": 1751550032601}], "start": 1751549934951, "stop": 1751550032744, "uuid": "ce3f107a-430f-44f1-9b0f-2ce8f1fcf00d", "historyId": "2acead2e5bc23ff9b4d5c8548b012223", "fullName": "Flujo completo de contratación de seguro en Queplan: No se permite agregar más de un cónyuge", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "queplan"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "Flujo completo de contratación de seguro en Queplan"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}