{"name": "No se permite RUT duplicado", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=138.0.7204.101)\nStacktrace:\n0   chromedriver                        0x0000000101034eb4 cxxbridge1$str$ptr + 2722840\n1   chromedriver                        0x000000010102cdbc cxxbridge1$str$ptr + 2689824\n2   chromedriver                        0x0000000100b7e3ec cxxbridge1$string$len + 90648\n3   chromedriver                        0x0000000100b58144 chromedriver + 131396\n4   chromedriver                        0x0000000100bed60c cxxbridge1$string$len + 545848\n5   chromedriver                        0x0000000100c06454 cxxbridge1$string$len + 647808\n6   chromedriver                        0x0000000100bb9834 cxxbridge1$string$len + 333408\n7   chromedriver                        0x0000000100ff7fd0 cxxbridge1$str$ptr + 2473268\n8   chromedriver                        0x0000000100ffb23c cxxbridge1$str$ptr + 2486176\n9   chromedriver                        0x0000000100fd9a18 cxxbridge1$str$ptr + 2348924\n10  chromedriver                        0x0000000100ffbaf8 cxxbridge1$str$ptr + 2488412\n11  chromedriver                        0x0000000100fcaaa8 cxxbridge1$str$ptr + 2287628\n12  chromedriver                        0x000000010101b9e8 cxxbridge1$str$ptr + 2619212\n13  chromedriver                        0x000000010101bb74 cxxbridge1$str$ptr + 2619608\n14  chromedriver                        0x000000010102c9f8 cxxbridge1$str$ptr + 2688860\n15  libsystem_pthread.dylib             0x0000000188369f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188364d34 thread_start + 8\n\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 11, in step_impl\n    context.driver.get(context.base_url)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given que el usuario accede al formulario de Queplan", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=138.0.7204.101)\nStacktrace:\n0   chromedriver                        0x0000000101034eb4 cxxbridge1$str$ptr + 2722840\n1   chromedriver                        0x000000010102cdbc cxxbridge1$str$ptr + 2689824\n2   chromedriver                        0x0000000100b7e3ec cxxbridge1$string$len + 90648\n3   chromedriver                        0x0000000100b58144 chromedriver + 131396\n4   chromedriver                        0x0000000100bed60c cxxbridge1$string$len + 545848\n5   chromedriver                        0x0000000100c06454 cxxbridge1$string$len + 647808\n6   chromedriver                        0x0000000100bb9834 cxxbridge1$string$len + 333408\n7   chromedriver                        0x0000000100ff7fd0 cxxbridge1$str$ptr + 2473268\n8   chromedriver                        0x0000000100ffb23c cxxbridge1$str$ptr + 2486176\n9   chromedriver                        0x0000000100fd9a18 cxxbridge1$str$ptr + 2348924\n10  chromedriver                        0x0000000100ffbaf8 cxxbridge1$str$ptr + 2488412\n11  chromedriver                        0x0000000100fcaaa8 cxxbridge1$str$ptr + 2287628\n12  chromedriver                        0x000000010101b9e8 cxxbridge1$str$ptr + 2619212\n13  chromedriver                        0x000000010101bb74 cxxbridge1$str$ptr + 2619608\n14  chromedriver                        0x000000010102c9f8 cxxbridge1$str$ptr + 2688860\n15  libsystem_pthread.dylib             0x0000000188369f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188364d34 thread_start + 8\n\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 11, in step_impl\n    context.driver.get(context.base_url)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1752524581580, "stop": 1752524581585}, {"name": "When ingresa datos de contratante con rut \"10638372-3\"", "status": "skipped", "start": 1752524581662, "stop": 1752524581662}, {"name": "And ingresa datos de beneficiario con rut \"10638372-3\" y hacer clic en siguiente paso", "status": "skipped", "start": 1752524581662, "stop": 1752524581662}, {"name": "Then debe mostrarse el mensaje de error con rut \"No puede haber mas de un perfil con el mismo número de identificación\" y el rut \"106383723\"", "status": "skipped", "start": 1752524581662, "stop": 1752524581662}], "start": 1752524569705, "stop": 1752524581662, "uuid": "7efe3988-7eea-45a0-9fe2-5d75fe9e1b54", "historyId": "8f75edfafed9d5b52c3aae5500685a1f", "fullName": "Flujo completo de contratación de seguro en Queplan: No se permite RUT duplicado", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "queplan"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "Flujo completo de contratación de seguro en Queplan"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}